#!/usr/bin/env python3
'''
sudo apt install python3-PyQt5
'''

VERSION = '0.0.1'
BUILD_DATE = '12/17/2022'

import sys, os, traceback
from traceback import StackSummary
from functools import partial
from decimal import Decimal as dec
from math import tan
from math import radians
from math import sqrt
from math import sin

from PyQt5 import uic
from PyQt5.QtWidgets import (QApplication, QMainWindow, QMessageBox,
	QDialog, qApp, QProgressBar)

#from libsegcalc import combo


sys.dont_write_bytecode = True

class MainWindow(QMainWindow):
	def __init__(self):
		super().__init__()
		if os.path.split(sys.argv[0])[0] == '/usr/bin':
			self.lib_path = '/usr/lib/libmesact'
			self.firmware_path = '/usr/lib/libmesact'
			self.image_path = '/usr/lib/libmesact'
			self.docs_path = '/usr/lib/libmesact'
			uic.loadUi(os.path.join(self.lib_path, 'segcalc.ui'), self)
		else:
			srcPath = os.path.split(os.path.realpath(sys.argv[0]))[0]
			self.lib_path = os.path.join(srcPath, 'libmesact')
			self.firmware_path = os.path.join(srcPath, 'firmware')
			self.image_path = os.path.join(srcPath, 'images')
			self.docs_path = os.path.join(srcPath, 'manuals')
			uic.loadUi(os.path.join(srcPath, 'segcalc.ui'), self)
		sys.excepthook = self.excepthook
		self.version = VERSION
		self.setWindowTitle(f'Segment Calcuator - Version {VERSION} - Build Date {BUILD_DATE}')
		self.progressBar = QProgressBar()
		self.statusBar().addPermanentWidget(self.progressBar)
		self.setupUI()
		self.setupConnections()
		self.show()

	def setupUI(self):
		self.segmentsLE.setText('8')
		self.odLE.setText('5')
		self.idLE.setText('2.5')
		self.kerfLE.setText('0.125')

	def setupConnections(self):
		self.calcPB.clicked.connect(self.calcSeg)

	def calcSeg(self):
		segments = int(self.segmentsLE.text())
		# use the radius of OD and ID
		outer_radius = float(self.odLE.text()) / 2
		inner_radius = float(self.idLE.text()) / 2

		#print(f'segments {segments} od {od} id {id}')
		A = (360 / segments) / 2
		C = 90
		B = C - A
		self.outerAngleaLB.setText(f'{A:.2f}')
		self.outerAnglebLB.setText(f'{B:.2f}')
		self.outerAnglecLB.setText(f'{C}')
		self.outerSidebLB.setText(f'{outer_radius:.2f}')
		outer_a = outer_radius * tan(radians(A))
		self.outerSideaLB.setText(f'{outer_a:.3f}')
		c = outer_radius / sin(radians(B))
		self.outerSidecLB.setText(f'{c:.3f}')
		self.lengthLB.setText(f'{outer_a * 2:.2f}')
		self.widthLB.setText(f'{outer_radius - inner_radius:.2f}')

		self.innerAnagleaLB.setText(f'{A:.2f}')
		self.innerAnaglebLB.setText(f'{B:.2f}')
		self.innerAnaglecLB.setText(f'{C}')
		inner_a = inner_radius * tan(radians(A))
		self.innerSideaLB.setText(f'{inner_a:.3f}')
		self.innerSidebLB.setText(f'{inner_radius:.3f}')
		self.innerSidecLB.setText(f'{inner_radius / sin(radians(B)):.3f}')
		if self.kerfLE.text() and self.lengthLE.text():
			outer_stock = ((segments / 2) * outer_a)
			inner_stock = ((segments / 2) * inner_a)
			kerfs = segments * float(self.kerfLE.text())
			stock = outer_stock + inner_stock + kerfs
			self.remainderLB.setText(f'{float(self.lengthLE.text()) - stock:.3f}')

		'''
		outerAngleA = 180/segments
		outerAngleB = dec(90-outerAngleA)
		sideb = length/2*tan(radians(outerAngleB))
		#(B2/2)*TAN(RADIANS(B7))
		# B2-(C2*TAN(RADIANS(A7))*2)
		innerLength = length-(width*tan(radians(outerAngleA))*2)
		self.innerLengthLB.setText(f'{innerLength:.3f}')
		self.odMaxLB.setText(f'{sideb*2:.3f}')
		innerAngleA = 180 / segments
		innerAngleb = 90-innerAngleA
		innerSideb = (innerLength/2)*tan(radians(innerAngleb))
		innerSidec = sqrt(((innerLength/2)*(innerLength/2)+(innerSideb*innerSideb)))
		self.idMinLB.setText(f'{innerSidec*2:.3f}')
		'''

	def errorMsg(self, text, title=None):
		msgBox = QMessageBox()
		msgBox.setIcon(QMessageBox.Warning)
		msgBox.setWindowTitle(title)
		msgBox.setText(text)
		msgBox.setStandardButtons(QMessageBox.Cancel | QMessageBox.Ok)
		returnValue = msgBox.exec()
		if returnValue == QMessageBox.Ok:
			return True
		else:
			return False

	def errorMsgOk(self, text, title=None):
		msgBox = QMessageBox()
		msgBox.setIcon(QMessageBox.Warning)
		msgBox.setWindowTitle(title)
		msgBox.setText(text)
		msgBox.setStandardButtons(QMessageBox.Ok)
		returnValue = msgBox.exec()
		if returnValue == QMessageBox.Ok:
			return True
		else:
			return False

	def infoMsgOk(self, text, title=None):
		msgBox = QMessageBox()
		msgBox.setIcon(QMessageBox.Information)
		msgBox.setWindowTitle(title)
		msgBox.setText(text)
		msgBox.setStandardButtons(QMessageBox.Ok)
		returnValue = msgBox.exec()
		if returnValue == QMessageBox.Ok:
			return True
		else:
			return False

	def excepthook(self, exc_type, exc_value, tb):
		# extract the stack summary
		summary = traceback.extract_tb(tb)
		for frame_summary in summary:
			filename = frame_summary.filename
			frame_summary.filename = os.path.relpath(filename)

		# rebuild the traceback and build the error message
		msg = f'Mesact Version: {VERSION} Build Date: {BUILD_DATE}\n'
		msg += ''.join(traceback.format_list(StackSummary.from_list(summary)))
		msg += f'{exc_type.__name__}\n'
		msg += f'{exc_value}\n'
		msg += 'Please file an issue at\n'
		msg += 'https://github.com/jethornton/segcalc/issues'
		print(msg)
		self.errorMsgOk(msg, 'PROGRAM ERROR' )


app = QApplication(sys.argv)
ex = MainWindow()
sys.exit(app.exec_())


